const dataCar = [
  {
    id: 1,
    name: 'ELANTRA',
    priceCart: 'от 12 000 до 25 000 ₽',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car1.png`,
    type: 'eco',
    markNumber: 'K 761 HA 73',
  },
  {
    id: 2,
    name: 'i30 N',
    priceCart: 'от 10 000 до 32 000 ₽',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car2.png`,
    type: 'eco',
    markNumber: 'А 790 МК 73',
  },
  {
    id: 3,
    name: 'CRETA',
    priceCart: 'от 12 000 до 25 000 ₽',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car3.png`,
    type: 'eco',
    markNumber: 'Е 442 ВЕ 73',
  },
  {
    id: 4,
    name: 'SONATA',
    priceCart: 'от 10 000 до 32 000 ₽ ',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car4.png`,
    type: 'premium',
    markNumber: 'Е 090 ВЕ 73',
  },
  {
    id: 5,
    name: 'ELANTRA',
    priceCart: 'от 12 000 до 25 000 ₽',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car1.png`,
    type: 'premium',
    markNumber: 'А 098 ГЕ 73',
  },
  {
    id: 6,
    name: 'i30 N',
    priceCart: 'от 10 000 до 32 000 ₽',
    price: 0,
    img: `${process.env.PUBLIC_URL}/img/car2.png`,
    type: 'premium',
    markNumber: 'А 001 БВ 73',
  },
]

export default dataCar
